apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "docuquery.fullname" . }}
  labels:
    {{- include "docuquery.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "docuquery.selectorLabels" . | nindent 6 }}
